In [1]:
import tensorflow as tf

In [2]:
random_float = tf.random.uniform(shape=(3,3))
zero_vector = tf.zeros(shape=(3,3))

随机3x3 0 3x3

In [7]:
random_float

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.40424073, 0.34637153, 0.36063325],
       [0.18468797, 0.9913868 , 0.72382724],
       [0.95622706, 0.5895966 , 0.29092753]], dtype=float32)>

In [8]:
zero_vector

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

# 求导

In [9]:
x = tf.Variable(initial_value=5.)
with tf.GradientTape() as tape:
    y = tf.square(x)
    y_grad = tape.gradient(y,x)

In [10]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=25.0>

In [14]:
y_grad

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

# 求偏导

In [20]:
x = tf.constant([[1.,3.],[5.,7.]])
y = tf.constant([[1.],[2.]])

In [17]:
w = tf.Variable(initial_value = [[1.],[2.]])
b = tf.Variable(initial_value = 1.)

In [24]:
with tf.GradientTape() as tape:
    L = tf.square(tf.reduce_sum(tf.matmul(x,w)+b-y))
    w_grad,b_grad = tape.gradient(L,[w,b])

In [22]:
L

<tf.Tensor: shape=(), dtype=float32, numpy=625.0>

In [25]:
w_grad

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[300.],
       [500.]], dtype=float32)>

In [26]:
b_grad

<tf.Tensor: shape=(), dtype=float32, numpy=100.0>